# Generated by Django 4.2.7 on 2023-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text správy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas vytvorenia')),
            ],
        ),
    ]
