# Generated by Django 4.2.7 on 2024-03-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_refactoringtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refactoringtask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='refactoringtask',
            name='example_code',
        ),
        migrations.AddField(
            model_name='refactoringtask',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Očakávaný výstup po refaktorizácii.', null=True),
        ),
        migrations.AddField(
            model_name='refactoringtask',
            name='input_code',
            field=models.TextField(default='', help_text='Pôvodný kód na refaktorizáciu.'),
            preserve_default=False,
        ),
    ]
