# Generated by Django 4.2.7 on 2024-04-03 12:54

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_uploadedfile_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=myapp.models.PathAndRename('uploads')),
        ),
    ]
