# Generated by Django 5.2.8 on 2025-12-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_taskrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='refactoringtask',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=10),
        ),
        migrations.AlterField(
            model_name='refactoringtask',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Unit testy ktoré budú spúštané na kód (testovací súbor treba pridať manuálne.).', null=True),
        ),
        migrations.AlterField(
            model_name='refactoringtask',
            name='input_code',
            field=models.TextField(help_text='Pôvodný kód na refaktorizáciu vložte sem.'),
        ),
    ]
